<?php
namespace Skincare\SiteKit\Widgets;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

use \Elementor\Widget_Base;
use \Elementor\Controls_Manager;

class Sk_Shipping_Page_Section extends Widget_Base {
	public function get_name() { return 'sk_shipping_page_section'; }
	public function get_title() { return __( 'Shipping: Page Section', 'skincare' ); }
	public function get_icon() { return 'eicon-text-area'; }
	public function get_categories() { return [ 'skincare-content' ]; }

	protected function render() {
		?>
		<div class="sk-shipping-section sk-page-content">
			<div class="sk-container">
				<div class="sk-content-wrapper">
					<h2><span style="text-decoration: underline;"><strong>Shipping Policy</strong></span></h2>

					<!-- Static Content from Reference -->
					<h3 class="p-rich_text_section">🎄Festive Delivery Update 🎄</h3>
					<div class="p-rich_text_section">
						<span aria-label="" class="c-mrkdwn__br" data-stringify-type="paragraph-break"></span>Please note that due to the festive period, there may be slight delays to deliveries as our courier partners will be operating reduced services. <span aria-label="" class="c-mrkdwn__br" data-stringify-type="paragraph-break"></span>There will be no courier collections from our warehouse on the following dates:<br aria-hidden="true">
					</div>
					<ul data-stringify-type="unordered-list" data-list-tree="true" class="p-rich_text_list p-rich_text_list__bullet p-rich_text_list--nested" data-indent="0" data-border="0">
						<li data-stringify-indent="0" data-stringify-border="0">Christmas Day (25th December)</li>
						<li data-stringify-indent="0" data-stringify-border="0">Boxing Day (26th December)</li>
						<li data-stringify-indent="0" data-stringify-border="0">New Year’s Day (1st January)</li>
					</ul>
					<div class="p-rich_text_section">
						<span>Orders placed during this time will be processed as quickly as possible and dispatched once courier services resume. We really appreciate your patience and understanding during this busy period.</span><span aria-label="" class="c-mrkdwn__br" data-stringify-type="paragraph-break"></span><span>Thank you so much for your continued support, and we wish you a lovely festive season!&nbsp;</span>
					</div>
					<div class="p-rich_text_section">
						<span></span><br>
					</div>
					<div class="p-rich_text_section">
						<p>We aim to dispatch orders within 24 to 48 business hours from the moment of order creation. Business hours are Monday to Friday, from 08:00 AM to 5:00 PM British Time, excluding weekends and UK bank holidays.</p>
					</div>

					<h3><span>Subscription boxes</span></h3>
					<p><span><b data-stringify-type="bold">Please note:</b> Our free delivery offer on orders over £30 does not apply to subscription boxes. Subscription boxes are excluded from all promotional discounts and shipping offers.</span><span></span></p>

					<h3><strong><u>UK Delivery</u><span>&nbsp;</span>- Tracked Delivery</strong></h3>
					<p><em>United Kingdom, Isle of Man, Jersey, Guernsey</em></p>
					<ul>
						<li><strong>Free</strong>&nbsp;<strong>Standard Delivery</strong> on orders over £30 - (2-3 working days from dispatch)&nbsp;</li>
						<li><strong>Free Inpost parcel locker delivery</strong> on orders over £30 ( 2 working days from dispatch)*</li>
						<li><strong>Free Next Day Delivery</strong> on orders over £150 (1 working day from dispatch)</li>
						<li>£3.99 - Royal Mail&nbsp;Tracked Standard Delivery (2-3 working days from dispatch)&nbsp;</li>
						<li>£3.99 - Inpost parcel locker delivery (2 working days from dispatch)*</li>
						<li>£5.50 - Royal Mail Tracked First Class Delivery &nbsp;(1-2 working days from dispatch)&nbsp;</li>
					</ul>
					<p>*Available in mainland UK only</p>

					<p><span><strong><span style="text-decoration: underline;"><span style="color: #ff2a00; text-decoration: underline;">Important international delivery information:</span></span></strong></span></p>
					<p>All orders are dispatched from the United Kingdom, and as such, parcels may be subject to additional customs duties or taxes upon arrival in your destination country. Please note that Skin Cupid is not responsible for any customs charges or taxes applied to your order, as all fees incurred during or after shipping (tariffs, taxes, etc.) are the responsibility of the customer.</p>
					<p><span>If&nbsp;there has been no progress with your shipment within 14 days or</span>&nbsp;you have issues with your order, please email us at hello@skincupid.co.uk and we will try our best to help.</p>
					<p><strong>Please note that we cannot deliver to PO Boxes outside of the UK.</strong></p>
					<p>&nbsp;</p>

					<h3><span style="font-weight: 400;">Customs and VAT Fees</span></h3>
					<p><span>If your order is returned&nbsp;because&nbsp;customs or VAT fees&nbsp;generated by customs in the recipient's country have been declined by the customer, we will process a refund deducting shipping costs.</span></p>

					<h3><span style="font-weight: 400;">Exceptions / Non-Returnable Items</span></h3>
					<p><span style="font-weight: 400;">Items that cannot be returned include: sale items, gift cards, and any items that have been opened or used.</span></p>

					<h3><span style="font-weight: 400;">Refund Process</span></h3>
					<p><span>Once we receive and inspect your return, we'll assess it to ensure it meets our return policy.</span></p>
					<p><span>If approved, the refund will be issued only to your original payment method. You will receive an email confirmation of the refund. Please allow several days for your bank or credit card company to process and post the refund.</span></p>
					<p><span>Any applicable fee deductions, including those for orders with free shipping, will be applied.</span></p>
					<p><span>If you have any questions or need further assistance, please reach out to us at hello@skincupid.co.uk. Thank you for shopping with us!</span></p>
					<p>&nbsp;</p>
				</div>
			</div>
		</div>
		<?php
	}
}
